# Generated by Django 4.0.3 on 2023-06-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Customer',
            new_name='customer',
        ),
    ]
