# Generated by Django 4.0.3 on 2023-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
